### ISSUE TITLE
Accepter Only connects to one emitter at a time

### ISSUE THREAD

**Issue by therealbenpai** [German-Immersive-Railroading-Community/GIRC-Redstone#150]
When attempting to link an accepter to multiple emitters, it overrides the old connection(s) and adds the new one. You can link an emitter to multiple accepters though

**Comment by MrTroble** [comment]
Yes, the system is designed as a 1:n association hence this is actually intended. So I take this as a feature request?

**Comment by therealbenpai** [comment]
wait, this is a bug, not an enhancement. I was saying that it would overwrite it, which was not what was expected

**Comment by therealbenpai** [comment]
Due to Github not properly sending me notifications for any of the issues I have submitted, I would prefer if you emailed me for any updates. My email is sparty182020@gmail.com. If this doesn't work out, you can still comment here, It'll just make it easier for me to know once you respond to my issue.

**Comment by MrTroble** [comment]
Ok let me clear this up: The linking tool resets it self after each linkage in order to prevent people from accidentally linking the same accepter to multiple emitters. How ever you can link an acceptor to multiple emitters, the emitters don't reset after linking to an other. You just need to readd the accepter to the linking tool by clicking on it again afterwards you can add the acceptor to an other emitter and both should be linked

**Comment by MrTroble** [comment]
Or are we mixing acceptors and emitters up? I am actually a bit confused tbh, because you can't link multiple acceptors to an emitter, the system is not designed that way

**Comment by therealbenpai** [comment]
It seems i must have misunderstood something because I assumed you could link multiple accepters to an emitter

**Comment by MrTroble** [comment]
There is an update in our backpipe to enable it in the future tho
